### PR TITLE
fix: replaced MinioClient to IMinioClient in HealthChecks

### PR DESCRIPTION
**Pull request by lukashev-di**

### CODE REVIEW

**Comment by lukashev-di** [comment]
Wait for review))

**Comment by sergeyshaykhullin** [comment]
@lukashev-di Could you please resolve conflicts?

**Comment by lukashev-di** [comment]
> @lukashev-di Could you please resolve conflicts?

Yes

**Comment by poganytamas** [comment]
Any news on that PR? I need my health check back ;)

**Review by sergeyshaykhullin — APPROVED** [review]

**Pull request merged**
